# Values for nsmm-chart.

# Installation mode: production, or test
installation:
  mode: test
  db: 
    persistent: false

pgadmin:                  # PgAdmin, deployed only in test installation
  image:
    repo: docker.io/bitnami/phppgadmin
    tag: 7
  service:
    exposedport: 30000   # Port exposed to the outside world, with the NodePort

database:
  name: nsmm
  username: root
  password: root 
  image:
    repo: postgres
    tag: 10-alpine
  service:
    name: nsmm-db-service
    port: 5432
  volume: 
    claimName: nsmm-db-claim

nsmm:
  # Trace, Debug, Info, Warning, Error, Fatal and Panic
  log:
    level: Trace
  image:
    repo: ghcr.io/5gzorro/network-service-mesh-manager/nsmm
    tag: latest
    privateregistry: false
  service:
    port: 8080            # Port exposed internally, to other services in the cluster
    exposedport: 30001    # Port exposed to the outside world, with the NodePort
  networks:
    gatewayNetworkNamePrefix: "<>"
    exposedNetworksNamePrefix: "<>"
    privateVpnRange: "192.168.1.1/24"
  vim:                    # Vim type can be none, or openstack - none for testing
  - name: "vim1"
    type: "<vim_type>"
    identityEndpoint: "<identity_endpoint>"
    username: "<username>"
    password: "<password>"
    tenantID: "<tenant_id>"
    domainID: "<domain_id>"
    floatingNetworkName: "<floating_net_name>"
    floatingNetworkID: "<floating_net_id>"
  - name: "vim2"
    type: "<vim_type>"
    identityEndpoint: "<identity_endpoint>"
    username: "<username>"
    password: "<password>"
    tenantID: "<tenant_id>"
    domainID: "<domain_id>"
    floatingNetworkName: "<floating_net_name>"
    floatingNetworkID: "<floating_net_id>"
  vpnaas:
    port: 8080
    environment: local