// Package NsmmApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package NsmmApi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/bNhD+KwQ3YC2gxElaFKuBYui6oPDQpUFa5EtbBLR0stnJpEJSSY3A/30gKVl8",
	"81vmutunNiRF3j1399xD+gHnfFZzBkxJPHzAMp/CjJj/ngvBxRXImjMJeqAAmQtaK8oZHtppJNr5zwxn",
	"GL6RWV2ZtaBn8RBPiIJ7MkelWXvbgFRQIFnRHFDBQSLGFYJvVCqJFxmuBa9BKArS2eQBq3kNeIilEpRN",
	"8GKRYb0XFVDg4ad22ZcMK6r06fiKc4U+zmswx3p+vLX2XHB1bg/Nus35+CvkShvRrnlvByLH7Tiyg2PK",
	"Jqh1MkDgmwLBSHVEazzEOMO0sP/OCCMTmAFTyylnqOZC2UED0lH3lWzGDNqZu5odUaZAlCSHfqj7NMbR",
	"NSVC01q2HNYbT0Do8cDSxJeR4Yk1vR+pydatxFTg5YoVK44NUoQWLqDLY1fmjJ8CiRy55FK1i37nxTzO",
	"kg/mBMRLpKaAakHviAKkD/WyxAmyLKYN3E9v3WCfvjw7Pn3x6/Hp8emLwdnLOLSPAzdAp13nILQSmNDv",
	"9dBcX1684YxBrkFZgZMFibKSixnRg4gBFFAgxVEuQKNG0PXlBcqXO/kQCphxBTcSxB2Im66k/NG+qgSv",
	"wK2oG8VvBBRUmFpPFE+8fegCLZHeFb16hd68G51ffOxR6WORsudxG/EqwcZX+rs22TRY9pwM0RJRhUiu",
	"JCISEfTh/Or6/ApxgUh7BqLMfNXDa2EPcMZ2dfaZ2S0M4a/IOB/T0NRR6GVqqyBDjdPbJGWQbqn0bJy1",
	"JZ00grjZuY7Bt2Punen339Dskq3DnuicGZ4Q77eJBz2k1oNqSz7GNcgBVnJT4O1SQISZiq9Iw/JpkMZd",
	"inZH/BVwaFuafkdcFuyNIGziD64MVbxVilbDnVev2a47RafGZ/g7blMJYSDisGkzNO8aA9vtmJzNjkhN",
	"taQAIW20To9Pjk+0V7wGpieH+NnxyfEZznBN1NQgN2hFkPljYruORtacPdL97S10pknzoSAzUCAkHn4K",
	"06Nh9LYBRAtgipYUREdtpkFpLaVX3TYgdIkzMjPg6rmR6e5GxKZw/6KBt0rQGHp2chIn5xF6XVWdqJNt",
	"EyrQZ3ZkbOgkbWtSoGo1TM9Pnutdc84UMIMEqeuK5gaLwVepT3lwrPxZQImH+KdBr8UHrRAf+CrcxMy3",
	"9oIvTS15wwq7puYyEQInPSS2OQhSdSW6F3tDgZCwuJVGOS1EQh/dc/H3b9gtECUaWESBOz0cxG+dS4y9",
	"uuRc6OZWzbvssGE/OZxNf354f4HGvJibG1Rrj7Xi2eGsOEKjEhG07pZHKgGkmLeXvK6IrFBAVC7nKUON",
	"PWSR9WwyeKDFwpZoBQrilP7DjHdJbco/SJTncYX34dOy7A4KnYdLNxwUA302q7mUdEwr0L3Kftt/l6H7",
	"Kc2nKOdNVaAxtC5psbXsc4XDDyGUPXIdnv4N2QZgE7emINhfXvoXo0RGLE0HRWglD06H28K4tv90H0Z9",
	"qGs9uu31nYcWEV8lmlAv1b5EGT7IvVa9Q76HPX7r5LfpS6qDc0ZQRdZR5AGAnjjiTzSMUTZ5+gNSyTdK",
	"s5srAPy0CuXB42p3QzgPWMieJbHY6TivIz0q0ZhImpOqmvtiHdEiQ1RJVFacKMomo0ur9qeA+ouIeQH4",
	"z4XYlZ0mmEZiGSmYjrNMsss+OCPDdZOSdM3a7PkOAm/N/Xnh32zSwi2huEeajVQjmDRwM7hfwuvHx5FZ",
	"/g7ahxVKKHp9cAOcE/aL0r2679DoSSdJnDFuLqHmpRlJRRQ8XdnIabmGA2Lmv6vZ49n/uma7N4D2Mc2B",
	"tddD9uDi4E3BvezLjvJ/AB18TJFcgunT66hsc7BXe9vR/uY4HpL5GyE0I3deRfnyA+JCYisMWTtEveHn",
	"JR01/6bSM/sWAvFQFJ7MhO/J4skHu8cS+Zapk+Dl18ingI6DYyp4TMmupd72wXirl6suQMtvtkHlHZXm",
	"Rw5SVcEvGQikIuOKyikUaDxPa6ztfN/ltrOnZN74xpRE67u+OcW/OG2VyglwO1j7K4qnG/oQkjyHWnk3",
	"+/9pt1q9dErs2uBd3m90Gwts8ND/oad3VzrdTm+cfXZ+8emcay/A9u0n+IVx4yuNmwEx4Pt6ytnF6xQd",
	"OzZG7zGr30324Nr+CSdL7pKHkOzwCLNY/BMAAP//vHpoTP4iAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

