// Package NsmmApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package NsmmApi

// Error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// Subnet of the private net
type PostGatewayBody struct {
	SliceId string `json:"slice-id"`
	Subnet  string `json:"subnet"`
}

// Set of information needed to create a VPN connection
type PostGatewayVPNConnectionBody struct {
	// if role == CLIENT
	RemoteServerIp *string `json:"remote_server_ip,omitempty"`

	// if role == CLIENT
	RemoteServerPort *string `json:"remote_server_port,omitempty"`

	// Role of the VPN server, if it acts as a SERVER or a CLIENT in the connection creation
	Role string `json:"role"`

	// If role == CLIENT
	SubnetToRedirect *string `json:"subnet_to_redirect,omitempty"`
}

// PutGatewayConfigurationBody defines model for PutGatewayConfigurationBody.
type PutGatewayConfigurationBody struct {
	ExternalIp         string `json:"external-ip"`
	ManagementIp       string `json:"management-ip"`
	ManagementPort     string `json:"management-port"`
	VpnServerInterface string `json:"vpn-server-interface"`
	VpnServerPort      string `json:"vpn-server-port"`
}

// ResponseGatewayConfigurationObject defines model for ResponseGatewayConfigurationObject.
type ResponseGatewayConfigurationObject struct {
	ExternalIp     string `json:"external-ip"`
	ManagementIp   string `json:"management-ip"`
	ManagementPort string `json:"management-port"`
}

// Object describing gateway
type ResponseGatewayObject struct {
	Id      int    `json:"id"`
	SliceId string `json:"slice-id"`
	Status  string `json:"status"`
	Subnet  string `json:"subnet"`
}

// ResponseGatewaysListObject defines model for ResponseGatewaysListObject.
type ResponseGatewaysListObject []ResponseGatewayObject

// GetGatewaysParams defines parameters for GetGateways.
type GetGatewaysParams struct {
	// unique identifier of the slice
	SliceId *string `json:"sliceId,omitempty"`
}

// PostGatewaysJSONBody defines parameters for PostGateways.
type PostGatewaysJSONBody PostGatewayBody

// PutGatewaysIdConfigurationJSONBody defines parameters for PutGatewaysIdConfiguration.
type PutGatewaysIdConfigurationJSONBody PutGatewayConfigurationBody

// PostGatewaysIdVpnConnectionsJSONBody defines parameters for PostGatewaysIdVpnConnections.
type PostGatewaysIdVpnConnectionsJSONBody PostGatewayVPNConnectionBody

// PostGatewaysJSONRequestBody defines body for PostGateways for application/json ContentType.
type PostGatewaysJSONRequestBody PostGatewaysJSONBody

// PutGatewaysIdConfigurationJSONRequestBody defines body for PutGatewaysIdConfiguration for application/json ContentType.
type PutGatewaysIdConfigurationJSONRequestBody PutGatewaysIdConfigurationJSONBody

// PostGatewaysIdVpnConnectionsJSONRequestBody defines body for PostGatewaysIdVpnConnections for application/json ContentType.
type PostGatewaysIdVpnConnectionsJSONRequestBody PostGatewaysIdVpnConnectionsJSONBody

