// Package NsmmApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package NsmmApi

// Error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// Object describing gateway
type GatewayObject struct {
	ExternalIp     *string `json:"external-ip,omitempty"`
	Id             int     `json:"id"`
	ManagementIp   *string `json:"management-ip,omitempty"`
	ManagementPort *string `json:"management-port,omitempty"`
	SliceId        string  `json:"slice-id"`
	Subnet         string  `json:"subnet"`
	VpnInterface   *string `json:"vpn-interface,omitempty"`
	VpnPort        *string `json:"vpn-port,omitempty"`
}

// Subnet of the private net
type PostGatewayBody struct {
	SliceId string `json:"slice-id"`
	Subnet  string `json:"subnet"`
}

// Set of information needed to create a VPN connection
type PostGatewayVPNConnectionBody struct {
	// if role == CLIENT
	RemoteServerIp *string `json:"remote_server_ip,omitempty"`

	// if role == CLIENT
	RemoteServerPort *string `json:"remote_server_port,omitempty"`

	// Role of the VPN server, if it acts as a SERVER or a CLIENT in the connection creation
	Role string `json:"role"`

	// If role == CLIENT
	SubnetToRedirect *string `json:"subnet_to_redirect,omitempty"`
}

// PutGatewayConfigurationBody defines model for PutGatewayConfigurationBody.
type PutGatewayConfigurationBody struct {
	ExternalIp     string `json:"external-ip"`
	ManagementIp   string `json:"management-ip"`
	ManagementPort int    `json:"management-port"`
}

// Info to configure and to launch the VPN server in the GatewayVM
type PutGatewayVPNConfigurationBody struct {
	ServerInterface string `json:"server_interface"`
	ServerIpRange   string `json:"server_ip_range"`
	ServerPort      string `json:"server_port"`
}

// GetGatewaysParams defines parameters for GetGateways.
type GetGatewaysParams struct {
	// unique identifier of the slice
	SliceId *string `json:"sliceId,omitempty"`
}

// PostGatewaysJSONBody defines parameters for PostGateways.
type PostGatewaysJSONBody PostGatewayBody

// PutGatewaysIdConfigurationJSONBody defines parameters for PutGatewaysIdConfiguration.
type PutGatewaysIdConfigurationJSONBody PutGatewayConfigurationBody

// PutGatewaysIdVpnConfigurationJSONBody defines parameters for PutGatewaysIdVpnConfiguration.
type PutGatewaysIdVpnConfigurationJSONBody PutGatewayVPNConfigurationBody

// PostGatewaysIdVpnConnectionsJSONBody defines parameters for PostGatewaysIdVpnConnections.
type PostGatewaysIdVpnConnectionsJSONBody PostGatewayVPNConnectionBody

// PostGatewaysJSONRequestBody defines body for PostGateways for application/json ContentType.
type PostGatewaysJSONRequestBody PostGatewaysJSONBody

// PutGatewaysIdConfigurationJSONRequestBody defines body for PutGatewaysIdConfiguration for application/json ContentType.
type PutGatewaysIdConfigurationJSONRequestBody PutGatewaysIdConfigurationJSONBody

// PutGatewaysIdVpnConfigurationJSONRequestBody defines body for PutGatewaysIdVpnConfiguration for application/json ContentType.
type PutGatewaysIdVpnConfigurationJSONRequestBody PutGatewaysIdVpnConfigurationJSONBody

// PostGatewaysIdVpnConnectionsJSONRequestBody defines body for PostGatewaysIdVpnConnections for application/json ContentType.
type PostGatewaysIdVpnConnectionsJSONRequestBody PostGatewaysIdVpnConnectionsJSONBody

