name: NSMM Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-login-and-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -o nsmm cmd/nsmm/main.go
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/5gzorro/network-service-mesh-manager/nsmm:latest